### ISSUE TITLE
Support modifying `buildhistorylimit` on the image resource

### ISSUE THREAD

**Issue by mgibson1121** [buildpacks-community/kpack-cli#172]
Users frequently ask why build pods are left behind and view this as an undesirable behavior because it creates clutter.  So far we have instructed these users to modify `successfulbuildhistorylimit` and `failedbuildhistorylimit` on the kpack image if the default pod retention configuration is not desired.  Given how frequently we get questions about this, seems worth it to invest in adding these fields as configurable flags on `kp image create`.

**Comment by vrabbi** [comment]
is this planned? this would be very helpful for many of our customers using kpack.

**Comment by vrabbi** [comment]
any chance of getting this?

**Comment by mgibson1121** [comment]
Looking at adding it to the roadmap for the upcoming quarter.
