### ISSUE TITLE
Need installation instructions page

### ISSUE THREAD

**Issue by trisberg** [buildpacks-community/kpack-cli#189]
I couldn't find a page to link to for installation instructions - do you have one?

**Comment by matthewmcnew** [comment]
Good catch! We need to add installation instructions to the README. For now you can get pre-built binaries on the [releases](https://github.com/vmware-tanzu/kpack-cli/releases).

**Comment by chenbh** [comment]
Homebrew install instructions was added to the README in https://github.com/buildpacks-community/kpack-cli/commit/d0cc85476b0911ddf05d0b4125cea0d89e8caea4
