### ISSUE TITLE
Feedback:  It is difficult to realize the problem when builds pods do not spin up due to not having registry access

### ISSUE THREAD

**Issue by mgibson1121** [buildpacks-community/kpack-cli#194]
Feedback from VMware account teams working with a customer to using kpack.  

**Problem:**  When running `kp image create --wait` and the build pod cannot access the registry that contains the builder, an Image resource will successfully reconcile but a build pod won't spin up and no logs will stream.  The feedback is that because we don't throw an error as part of this process, it is difficult to determine that the user needs to to troubleshoot their secret configuration.

This strikes me as a difficult problem to solve, at least from within the context of `kp image create` because from a technical standpoint, creation of an image and the resulting build pod spinning up are distinct events.  So I can't see how we could directly address the request, which seems to be for an error to be shown as part of the output of `kp image create --wait` if a build pod does not spin up due to a registry access issue.  

How might we address this problem?  Because I agree that it is a little arcane to expect users to understand they need to `kubectl get builds` (I think only successful, failed, or executing builds show up in `kp build list`) and `kubectl get -o yaml` a specific build pod.

**Comment by matthewmcnew** [comment]
I think this should be a kpack issue about on when we officially report a build failure when a build pod results an image pull backoff.  If `--wait` is following a build and the build errors for any reason the `--wait` will exit. The problem is that kpack doesn't report the build pod as a failure ever on image pull backoff.

**Comment by ncarlson** [comment]
https://github.com/pivotal/kpack/pull/1146

**Comment by fcaroline2020** [comment]
When the build has `build.Status.ConditionSucceeded=False`, error message will be propagated to console and return

```
Creating Image Resource...
Uploading to 'index.docker.io/repo/test-source'...
        Uploading 'index.docker.io/repo/test-source@sha256:7d30bc441f7fb96160dd14bd9407f45bb70c5f14ad2a35457ef926f245cb50a8'
Image Resource "my-test-image" created
Build failed to start: secrets "registry-credentials" not found
```
