### ISSUE TITLE
--local-path should not assume a repository name

### ISSUE THREAD

**Issue by tylerphelan** [buildpacks-community/kpack-cli#249]
When using `kp image ... --local-path` a repository of name `<image-tag-repo>-source` is pushed to. There is no guarantee this repository exists or that permissions for `<image-tag-repo>` and `<image-tag-repo>-source`

Questions:
- Should we make a `--source-tag` flag for `--local-path` to describe the source tag location to write to?

**Comment by yaelharel** [comment]
This issue has 2 aspects:
* Check that the repository exists and there are enough permissions.
* Allow the user to decide what location to use.

More ideas to the new flag name:
* `--source-tag`
* `--local-path-destination-tag`
* `--local-path-dest-image`
