### ISSUE TITLE
Print the build number after triggering the image build

### ISSUE THREAD

**Issue by pranavek** [buildpacks-community/kpack-cli#269]
Say, a user triggered an image build using `kp image trigger <IMAGE_NAME>`. There is no reference to the build that got triggered by that execution.  Print the build number on the console output. This would help the user to correlate the trigger to a particular build from the build list.

https://github.com/vmware-tanzu/kpack-cli/blob/main/pkg/commands/image/trigger.go#L66 points to the relevant code segment.

**Comment by pranavek** [comment]
@chenbh Any idea when would the merged changes get released?

**Comment by chenbh** [comment]
@pranavek we normally link the issue to the PR so the merging the PR auto-closes this issue, I forgot to do that for this one.

As for release, we tend to release the CLI at the same time as a kpack release, which in this case would be kpack v0.12.0 targeted for sometime this week or the next.

**Comment by chenbh** [comment]
fyi @pranavek kp v0.12.0 just got released and is available from the releases page or homebrew
