### ISSUE TITLE
Same build number is getting printed after triggering the image build

### ISSUE THREAD

**Issue by Priyanka-Kotturi** [buildpacks-community/kpack-cli#354]
When the user triggers the build using `kp image trigger <IMAGE_NAME>`, it prints the build number in the console. Observed that it was printing the same build number which is there in the image before the trigger.  

If it prints the triggered build number in the console, that would help the user to get the status of the triggered build 

This issue is expected after the release of PR (https://github.com/buildpacks-community/kpack-cli/pull/344)

**Comment by pranavek** [comment]
It seems like the Kpack controller is updating the labels - https://github.com/buildpacks-community/kpack/blob/main/pkg/apis/build/v1alpha2/image_builds.go#L38
