### ISSUE TITLE
`kp build logs` should support timestamps

### ISSUE THREAD

**Issue by matthewmcnew** [buildpacks-community/kpack-cli#66]
## What
`kp build logs` should support a `--timestamp` flag that will prefix log lines with timestamp. This is equivalent to `kubectl logs  timestamp`.

## Why
Timestamps will be helpful to diagnose long builds and isolate unexpected behavior.

**Comment by tcdowney** [comment]
Any updates on this one? Would y'all be open to a contribution?

**Comment by ncarlson** [comment]
> Any updates on this one? Would y'all be open to a contribution?

Absolutely!
